[package]
name = "proudcat-rust"
version = "0.0.1"
authors = ["Felix C. Stegerman <flx@obfusk.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
